# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8fb52ec891c078f44f9c97099971d8486a64e843beb7eccd4032833bcb5aece2725fa6b3a192626b3ee923766680be954d3dbc91b3028debb1080bf032ff17ad

test:
  secret_key_base: 745937208a49473fd0a72bb4260d99572721becf5c170cd70cf954d98da3fffff2269d18ad76ef785af3b8abf4f07dc1cab1611fb9f5d09685636922448dfc45

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
